-- MySQL Script generated by MySQL Workbench
-- Mon Apr 15 23:37:25 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Status` (
  `id_status` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `type` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Role` (
  `id_role` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_role`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Team` (
  `id_team` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_team`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `confirmed_email` varchar(255) not null,
  `unique_code` VARCHAR(50) NULL,
  `password_hash` VARCHAR(100) NULL,
  `phone` VARCHAR(30) NOT NULL,
  `image_key` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `status_idstatus` INT NOT NULL,
  `role_idrole` INT NOT NULL,
  `Team_id_team` INT NULL,
  PRIMARY KEY (`id_user`),
  INDEX `fk_User_status_idx` (`status_idstatus` ASC) VISIBLE,
  INDEX `fk_User_role1_idx` (`role_idrole` ASC) VISIBLE,
  INDEX `fk_User_Team1_idx` (`Team_id_team` ASC) VISIBLE,
  CONSTRAINT `fk_User_status`
    FOREIGN KEY (`status_idstatus`)
    REFERENCES `mydb`.`Status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_role1`
    FOREIGN KEY (`role_idrole`)
    REFERENCES `mydb`.`Role` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Team1`
    FOREIGN KEY (`Team_id_team`)
    REFERENCES `mydb`.`Team` (`id_team`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Goal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Goal` (
  `id_goal` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(500) NOT NULL,
  `deadline` DATETIME NOT NULL,
  `target_value` DECIMAL(10,2) NOT NULL,
  `current_value` DECIMAL(10,2) NOT NULL,
  `id_user_responsible` INT NOT NULL,
  PRIMARY KEY (`id_goal`),
  INDEX `fk_Goal_User1_idx` (`id_user_responsible` ASC) VISIBLE,
  CONSTRAINT `fk_Goal_User1`
    FOREIGN KEY (`id_user_responsible`)
    REFERENCES `mydb`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Priority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Priority` (
  `id_priority` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_priority`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Activity` (
  `id_activity` INT NOT NULL auto_increment,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `Priority_id_priority` INT NOT NULL,
  `Team_id_team` INT NOT NULL,
  PRIMARY KEY (`id_activity`),
  INDEX `fk_Activity_Priority1_idx` (`Priority_id_priority` ASC) VISIBLE,
  INDEX `fk_Activity_Team1_idx` (`Team_id_team` ASC) VISIBLE,
  CONSTRAINT `fk_Activity_Priority1`
    FOREIGN KEY (`Priority_id_priority`)
    REFERENCES `mydb`.`Priority` (`id_priority`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Activity_Team1`
    FOREIGN KEY (`Team_id_team`)
    REFERENCES `mydb`.`Team` (`id_team`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Offer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Offer` (
  `id_offer` INT NOT NULL AUTO_INCREMENT,
  `service` VARCHAR(50) NOT NULL,
  `offer_date` DATETIME NOT NULL,
  `value` DECIMAL(10,2) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `file_key` VARCHAR(100) NOT NULL,
  `Status_id_status` INT NOT NULL,
  `User_id_user` INT NOT NULL,
  PRIMARY KEY (`id_offer`),
  INDEX `fk_Offer_Status1_idx` (`Status_id_status` ASC) VISIBLE,
  INDEX `fk_Offer_User1_idx` (`User_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_Offer_Status1`
    FOREIGN KEY (`Status_id_status`)
    REFERENCES `mydb`.`Status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Offer_User1`
    FOREIGN KEY (`User_id_user`)
    REFERENCES `mydb`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`State`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`State` (
  `id_state` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `Statecol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_state`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`City` (
  `id_city` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `State_id_state` INT NOT NULL,
  PRIMARY KEY (`id_city`),
  INDEX `fk_City_State1_idx` (`State_id_state` ASC) VISIBLE,
  CONSTRAINT `fk_City_State1`
    FOREIGN KEY (`State_id_state`)
    REFERENCES `mydb`.`State` (`id_state`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Address` (
  `id_address` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(50) NOT NULL,
  `zip_code` VARCHAR(50) NOT NULL,
  `number` INT NOT NULL,
  `City_id_city` INT NOT NULL,
  PRIMARY KEY (`id_address`),
  INDEX `fk_Address_City1_idx` (`City_id_city` ASC) VISIBLE,
  CONSTRAINT `fk_Address_City1`
    FOREIGN KEY (`City_id_city`)
    REFERENCES `mydb`.`City` (`id_city`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `id_client` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `cpf` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NULL,
  `company` VARCHAR(50) NOT NULL,
  `Address_id_address` INT NOT NULL,
  PRIMARY KEY (`id_client`),
  INDEX `fk_Client_Address1_idx` (`Address_id_address` ASC) VISIBLE,
  CONSTRAINT `fk_Client_Address1`
    FOREIGN KEY (`Address_id_address`)
    REFERENCES `mydb`.`Address` (`id_address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Result` (
  `idResult` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idResult`),
  UNIQUE INDEX `idResult_UNIQUE` (`idResult` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Call`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Call` (
  `id_call` INT NOT NULL AUTO_INCREMENT,
  `Offer_id_offer` INT NOT NULL,
  `Client_id_client` INT NOT NULL,
  `contact` VARCHAR(30) NOT NULL,
  `date` TIMESTAMP NOT NULL,
  `duration` DECIMAL(5,2) NOT NULL,
  `description` TEXT NOT NULL,
  `Result_idResult` INT NOT NULL,
  PRIMARY KEY (`id_call`),
  INDEX `fk_Call_Offer1_idx` (`Offer_id_offer` ASC) VISIBLE,
  INDEX `fk_Call_Client1_idx` (`Client_id_client` ASC) VISIBLE,
  INDEX `fk_Call_Result1_idx` (`Result_idResult` ASC) VISIBLE,
  CONSTRAINT `fk_Call_Offer1`
    FOREIGN KEY (`Offer_id_offer`)
    REFERENCES `mydb`.`Offer` (`id_offer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Call_Client1`
    FOREIGN KEY (`Client_id_client`)
    REFERENCES `mydb`.`Client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Call_Result1`
    FOREIGN KEY (`Result_idResult`)
    REFERENCES `mydb`.`Result` (`idResult`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contact` (
  `id_contact` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(100) NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_contact`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Client_Contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client_Contact` (
  `Client_id_client` INT NOT NULL,
  `Contact_id_contact` INT NOT NULL,
  PRIMARY KEY (`Client_id_client`, `Contact_id_contact`),
  INDEX `fk_Client_Contact_Contact1_idx` (`Contact_id_contact` ASC) VISIBLE,
  CONSTRAINT `fk_Client_Contact_Client1`
    FOREIGN KEY (`Client_id_client`)
    REFERENCES `mydb`.`Client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_Contact_Contact1`
    FOREIGN KEY (`Contact_id_contact`)
    REFERENCES `mydb`.`Contact` (`id_contact`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
